---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- as.character(round(runif(10)*100),10)
x
```
```{r}
logicBig <- (as.integer(x) > 50)

logicBig
```
```{r}
randomGrades <- sample(40:80,15,replace = T)
randomCredits <- sample(0:3,15,replace=T)
data3 <- list(
  成績=randomGrades,
  學分數=randomCredits
)
```
```{r}
passLogic <- data3$成績 >= 60
passLogic
passdata 
```
```{r}
str_sub(twDateTime,3,5)

```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```
```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],
        tz="America/New_York") -> nyDateTime

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],
        tz="Asia/Taipei") -> tpDateTime

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```
```{r}
library(lubridate)
a <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
timez1 <-with_tz(a, tz="Asia/Taipei")

ymd_hms_tzChange <- function(x,y,z){
  a <- ymd_hms(x,tz=y)
  timez1 <-with_tz(a, tzone = z)
  return(timez1)
}
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```

```{r}
date_convert_twYM<-function(x){
  yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(x,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
date_convert_twYM(twDates)->z
z
```
```{r}
date_convert_twYM <- function(twDates,dd="01"){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  yyyymmdd
}
```

