---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系"))
```

```{r}
typeof(studentMajors)
```

```{r}
class(studentMajors)
```
```{r}
levels(studentMajors)
```
```{r}
as.integer(studentMajors)
```

```{r}
birthplace <- factor(
  c("台北市","台北市","台中市","台北市","台中市")
)
class(birthplace)
levels(birthplace)
as.integer(birthplace)
```
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)

dtObject
typeof(dtObject)
as.integer(dtObject)
```

```{r}
as.double(dtObject)
as.double(dtObjectVector)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
Sys.timezone()
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```
```{r}
NewYorkDateTime <- with_tz(twDateTime,tzone = "America/New_York")
```
```{r}
typeof(twDateTime)
as.integer(twDateTime)
```
```{r}
typeof(NewYorkDateTime)
as.double(NewYorkDateTime)
```
```{r}
TWDT <- dmy_h("27-03-2019 15")
```
```{r}
NYDT <- mdy_hms("06-19-2000 15-05-05")
```
```{r}
TWDT <- dmy("11-09-2018")
```
```{r}
TWDT <- mdy("March 3,2019")
```
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+b
aaL <- a+aL
class(aaL)
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a+b
a-b
a*b
a/b
```
```{r}
c <- 4

c+a
```
```{r}
a <- ymd_hms("2019-03-18 14:04:00")
b <- ymd_hms("2019-03-18 14:05:50") 
a-b
b-a
```
```{r}
startingDate <- ymd("2000-02-17")
```
```{r}
a <-startingDate + years(1)
```

```{r}
x <- 5
y <- 7
(x ==y)
(x!=y)
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)
x2%in% y2
x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
x3%in% y3
```

```{r}
is.na(x2)
```
```{r}
sum(x2)
sum(x2, na.rm = TRUE)
```

```{r}
install.packages("readr")
```


```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
head(currency) # head 會顯示物件前六個元素值。
```
```{r}
levels(currency)
```

```{r}
class(currency)
```

```{r}
currency <- as.factor(currency)
class(currency)
```


```{r}
levels(currency)
```
```{r}
length(levels(currency))
```

```{r}
step1_extractLevelsVector <- levels(currency)
step1_extractLevelsVector
```

```{r}
step2_countVectorLength <- length(step1_extractLevelsVector)
```

```{r}
step2_countVectorLength
```

多少筆日元資料

```{r}
head(currency)
levels(currency)
```

```{r}
currency2 <- c("日元","美元","日元")
currency2
```

```{r}
sum(currency2 == "日元")
```

```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5=="女"
!(y5=="女")
```
```{r}
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
(x5 %in% greatTaipei) | (y5=="女")
```
```{r}
xor(x5 %in% greatTaipei, y5=="女")
```
```{r}
y5
(y5 == "女")
which(y5=="女")
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
sum(major == "經濟學系")
```

```{r}
sum(studentID == "5bdS6977b")
```

```{r}
sum(
  studentID == "5bdS6977b" &
    grade >= 60
)
```

```{r}
sum(
  major == "經濟學系" &
    courseType == "選"
)
```

```{r}
sum(
  major == "經濟學系" &
    courseType == "必"
) -> 分母
分母
```

```{r}
sum(
  major == "經濟學系" &
    courseType == "必" &
    grade < 60
) -> 分子
分子
```

```{r}
分子/分母
```
```{r}
install.packages("stringr")
```
```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```
```{r}
str_subset(course,"經濟學")
```
```{r}
str_detect(course,"經濟學")
```
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
系別<-str_sub(studentID,5,6)
系別
入學年<-str_sub(studentID,2,4)
入學年
```
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
str_c(month,day,sep="-")
```
```{r}
dates
str_replace(dates,"-","月")
```
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
birthday
y<-str_sub(birthday,1,4)
m<-str_sub(birthday,5,6)
d<-str_sub(birthday,7,8)
bday<-str_c("西元",y,"年",m,"月",d,"日")
bday
```













