---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

引入套件
```{r}
library(stringr)
```

no package
```{r}
install.packages("stringr")
```

subset
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```

```{r}
course
str_detect(course,"經濟學")
```


str_sub
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
major<- str_sub(studentID,5,6) # 學系號
major
```

```{r}
studentID
入學年<-str_sub(studentID,2,4)
入學年
```

# join

str_c
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
```

```{r}
str_c(month,"月",day,"日")
```


```{r}
month
day
str_c(month,day, sep="-")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
dates
str_split(dates,"-")
```

str_replace
```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
username
reponame
```

```{r}
"https://github.com"
username
reponame
str_c("https://github.com",username,reponame,sep="/")
```

```{r}
"https://github.com"
username[1:2]
reponame[1:2]
str_c("https://github.com",username[1:2],reponame[1:2],sep="/")

```

練習一
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```


```{r}
birthday[1:2]
y<-str_sub(birthday[1:2],1,4)
m<-str_sub(birthday[1:2],5,6)
d<-str_sub(birthday[1:2],7,8)
y
m
d
bday<-str_c("西元",y,"年",m,"月",d,"日")
bday
```

```{r}
birthday[1:2]
y<-str_sub(birthday[1:2],1,4)
m<-str_sub(birthday[1:2],5,6)
d<-str_sub(birthday[1:2],7,8)
y 
m2 <- str_replace(m,"0","")
d
d2 <- str_replace(d,"0","")
d2
bday<-str_c("西元",y,"年",m2,"月",d2,"日")
bday
```

民國年月
1. "099/01"變成"099", "01" (str_sub)
```{r}

```
2."099"變成 99 (hint: as.integer())
```{r}

```
3. 99+ 1911
```{r}

```
4. 2010 變成"2010" (hint: as.character())
```{r}

```
5. "2010","01", 合成 "2010/01"
```{r}


```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)

成績單[[1]]
成績單[["個經"]]
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][["三年級"]]
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5),  
  blueBox=c(TRUE,FALSE,TRUE,TRUE) 
)
```

```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]

extract1[[1]][[1]]
extract2[[1]]


```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單

```
```{r}
your_github_username <- "jonathanli619"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```
```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```
```{r}
logiCorrect <- str_length(birthday) ==8
logiCorrect
```

```{r}
a <- matrix(c(1:6), nrow=3, ncol=2) ##建立3x2的矩陣，分別填入1~6的值
a
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```
```{r}
chosenLETTERS <- LETTERS[1:16]
matObj1 <- matrix(chosenLETTERS,4,4)
matObj1
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
tolower(m) 
toupper(m) 
```
```{r}
matObj1 <-matrix(chosenLETTERS,5,3)
matObj1 
matObj11 <-matrix(chosenLETTERS,3,5)
matObj11
```
```{r}
matObj1[1,1]
matObj1[c(T,F,F,T,F),c(F,T,T)]
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
classSurvey[c(1:60),c(4,5)]
classSurvey[,c(4,5)]
```



